"""create tables

Revision ID: 0a8fe18bf404
Revises: 488b684c1b2b
Create Date: 2023-09-23 10:46:22.232461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8fe18bf404'
down_revision = '488b684c1b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
