"""create tables

Revision ID: e1a525162569
Revises: 0a8fe18bf404
Create Date: 2023-09-23 10:48:52.288230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a525162569'
down_revision = '0a8fe18bf404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('image', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'price')
    op.drop_column('plants', 'image')
    # ### end Alembic commands ###
